#pragma once

#include "bmcl/core/memwriter.h"
#include "bmcl/core/memreader.h"
#include "bmcl/core/status.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    BMCL_INSTR_PUSH8 = 0,
    BMCL_INSTR_PUSH16,
    BMCL_INSTR_PUSH32,
    BMCL_INSTR_PUSH64,
    BMCL_INSTR_CONVERT_I8_TO_I32,
    BMCL_INSTR_CONVERT_I8_TO_U32,
    BMCL_INSTR_CONVERT_U8_TO_I32,
    BMCL_INSTR_CONVERT_U8_TO_U32,
    BMCL_INSTR_CONVERT_I16_TO_I32,
    BMCL_INSTR_CONVERT_I16_TO_U32,
    BMCL_INSTR_CONVERT_U16_TO_I32,
    BMCL_INSTR_CONVERT_U16_TO_U32,
    BMCL_INSTR_CONVERT_I32_TO_I8,
    BMCL_INSTR_CONVERT_I32_TO_U8,
    BMCL_INSTR_CONVERT_I32_TO_I16,
    BMCL_INSTR_CONVERT_I32_TO_U16,
    BMCL_INSTR_CONVERT_I32_TO_I64,
    BMCL_INSTR_CONVERT_I32_TO_U64,
    BMCL_INSTR_CONVERT_I32_TO_FLOAT,
    BMCL_INSTR_CONVERT_I32_TO_DOUBLE,
    BMCL_INSTR_CONVERT_U32_TO_I8,
    BMCL_INSTR_CONVERT_U32_TO_U8,
    BMCL_INSTR_CONVERT_U32_TO_I16,
    BMCL_INSTR_CONVERT_U32_TO_U16,
    BMCL_INSTR_CONVERT_U32_TO_U64,
    BMCL_INSTR_CONVERT_U32_TO_I64,
    BMCL_INSTR_CONVERT_U32_TO_FLOAT,
    BMCL_INSTR_CONVERT_U32_TO_DOUBLE,
    BMCL_INSTR_CONVERT_I64_TO_I32,
    BMCL_INSTR_CONVERT_I64_TO_U32,
    BMCL_INSTR_CONVERT_I64_TO_FLOAT,
    BMCL_INSTR_CONVERT_I64_TO_DOUBLE,
    BMCL_INSTR_CONVERT_U64_TO_I32,
    BMCL_INSTR_CONVERT_U64_TO_U32,
    BMCL_INSTR_CONVERT_U64_TO_FLOAT,
    BMCL_INSTR_CONVERT_U64_TO_DOUBLE,
    BMCL_INSTR_CONVERT_FLOAT_TO_I32,
    BMCL_INSTR_CONVERT_FLOAT_TO_U32,
    BMCL_INSTR_CONVERT_FLOAT_TO_I64,
    BMCL_INSTR_CONVERT_FLOAT_TO_U64,
    BMCL_INSTR_CONVERT_FLOAT_TO_DOUBLE,
    BMCL_INSTR_CONVERT_DOUBLE_TO_I32,
    BMCL_INSTR_CONVERT_DOUBLE_TO_U32,
    BMCL_INSTR_CONVERT_DOUBLE_TO_I64,
    BMCL_INSTR_CONVERT_DOUBLE_TO_U64,
    BMCL_INSTR_CONVERT_DOUBLE_TO_FLOAT,
    BMCL_INSTR_ADD_I8,
    BMCL_INSTR_ADD_I16,
    BMCL_INSTR_ADD_I32,
    BMCL_INSTR_ADD_I64,
    BMCL_INSTR_ADD_U8,
    BMCL_INSTR_ADD_U16,
    BMCL_INSTR_ADD_U32,
    BMCL_INSTR_ADD_U64,
    BMCL_INSTR_ADD_FLOAT,
    BMCL_INSTR_ADD_DOUBLE,
    BMCL_INSTR_SUB_I8,
    BMCL_INSTR_SUB_I16,
    BMCL_INSTR_SUB_I32,
    BMCL_INSTR_SUB_I64,
    BMCL_INSTR_SUB_U8,
    BMCL_INSTR_SUB_U16,
    BMCL_INSTR_SUB_U32,
    BMCL_INSTR_SUB_U64,
    BMCL_INSTR_SUB_FLOAT,
    BMCL_INSTR_SUB_DOUBLE,
    BMCL_INSTR_MULT_I8,
    BMCL_INSTR_MULT_I16,
    BMCL_INSTR_MULT_I32,
    BMCL_INSTR_MULT_I64,
    BMCL_INSTR_MULT_U8,
    BMCL_INSTR_MULT_U16,
    BMCL_INSTR_MULT_U32,
    BMCL_INSTR_MULT_U64,
    BMCL_INSTR_MULT_FLOAT,
    BMCL_INSTR_MULT_DOUBLE,
    BMCL_INSTR_DIV_I8,
    BMCL_INSTR_DIV_I16,
    BMCL_INSTR_DIV_I32,
    BMCL_INSTR_DIV_I64,
    BMCL_INSTR_DIV_U8,
    BMCL_INSTR_DIV_U16,
    BMCL_INSTR_DIV_U32,
    BMCL_INSTR_DIV_U64,
    BMCL_INSTR_DIV_FLOAT,
    BMCL_INSTR_DIV_DOUBLE,
} bmcl_sci_instr_type_t;

typedef struct {
    bmcl_memreader_t bytecode;
    bmcl_memwriter_t stack;
} bmcl_sci_interp_t;

void bmcl_sci_interp_init(bmcl_sci_interp_t* self, const void* bytecode, size_t bytecode_size, void* stack,
                          size_t stack_size);

#if BMCL_HAVE_MALLOC

bmcl_sci_interp_t* bmcl_sci_interp_create(const void* bytecode, size_t bytecode_size, size_t stack_size);

void bmcl_sci_interp_destroy(bmcl_sci_interp_t* self);

#endif

bmcl_status_t bmcl_sci_interp_exec_next(bmcl_sci_interp_t* self);

#ifdef __cplusplus
}
#endif
